name: my_sec_workflow

on: push

jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: run script
              run: ./script2.sh

            - run: mkdir path
            - run: echo hello > path/world.txt
            - uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: path/world.txt
