name: my_sec_workflow

on: push

jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: run script
              run: 
                |
                chmod +x script2.sh
                ./script2.sh

            - run: echo hello > dragon.txt
            - uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: dragon.txt
