name: my first workflow | shell script

on:
    push:
        branches: [main]

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: list files
              run: ls -ltra
            
            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: run shell script
              run: 
                |
                chomod +x script.sh
                ./script.sh